### ISSUE TITLE
Чит

### ISSUE THREAD

**Issue by kln4a** [leshadarko/vue-task#1]
1) Подключение шрифтов я бы сделал по другому. Все шрифты из одного семейства Roboto, поэтому правильно будет сделать т.о.:
```css
  @font-face {
    font-family: 'Roboto';
    ...// начертание Light
    font-weight: 300;
  }

  @font-face {
    font-family: 'Roboto';
    ...// начертание Regular
    font-weight: 400;
  }

  @font-face {
    font-family: 'Roboto';
    ...// жирное начертание
    font-weight: 700;
  }

 // таким же образом и font-style

  @font-face {
    font-family: 'Roboto';
    ...// жирное начертание
    font-style: italic;
  }
```
Теперь использование в коде будет более логичным, например

БЫЛО:
```css
.text h1 {
  font-family: 'robotobold';
}
.text p {
  font-family: 'robotoregular';
}
```
СТАЛО:
```css
.text {
  font-family: 'Roboto';
}
.text h1 {
  font-weight: bold;
}
```
2) Есть проблемы с отступами между элементами в соответствии с макетом. Забыл добавить border-radius у этих блоков https://s.mail.ru/4BsA/ZowELU5xM.
3) Перепутаны местами https://s.mail.ru/3JfV/8j2ax6MZx (справа +)
4) Один из элементов у меня поехал https://s.mail.ru/4gYV/DbwAziTEs. 
Решение добавить для .switch flex: none;

Разбивать на отдельные (css, js, html) не надо конечно.
Стейт правильно организован, БЭМ выдержан, в остальном все ок.

Рекомендации: 
-) Переменные для цветов объявляются в каждом компоненте, на мой взгляд более логично сделать один конфиг, и уже его импортировать в компонентах, чтобы в одном месте все было.
-) добавить eslint для js
-) не торопиться и более внимательно прорабатывать макет, видно что ошибки не серьезные, но при детальном просмотре бросаются в глаза
-) я бы App.vue еще раздробил на компоненты
